version: '3'

services:
  db:
    build: services/db
    ports:
      - 7687:7687
    volumes:
      - store:/data
  db_shell:
    depends_on:
      - db
    build: services/db_shell
    tty: true
    stdin_open: true
    command: bash -c "connect"

volumes:
  store:
