openapi: 3.0.0
info:
  title: Bipolar Bridges Data Services Interface
  version: '0.2'
  license:
    name: MIT
  description: Provides endpoints for general-purpose data import and acquisition within the BB infrastructure.
  contact:
    name: Rowan Lindsay
    email: rowdl22@students.cs.ubc.ca
servers: []
paths:
  /appUser:
    post:
      summary: Create an App User.
      tags: []
      responses:
        '201':
          description: Created
          content:
            application/json:
                schema:
                  description: 'Creation message'
                  type: object
                  properties:
                    message:
                      type: string
                      minLength: 1
                  required:
                    - message
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                description: 'Error Cause'
                type: object
                properties:
                  message:
                    type: string
                    minLength: 1
                required:
                  - message
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                description: 'Error Cause'
                type: object
                properties:
                  message:
                    type: string
                    minLength: 1
                required:
                  - message
      operationId: post-appUser
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                id:
                  type: string
                  minLength: 1
              required:
                - id
            examples: {}
      security:
        - import-key: []
    get: 
      summary: Get information about a specific appUser
      tags: []
      responses:
        '403':
          description: Forbidden
          content:
            application/json:
                schema:
                  description: 'Message'
                  type: object
                  properties:
                    message:
                      type: string
                      minLength: 1
                  required:
                    - message
        '200':
          description: Good
          content:
            application/json:
                schema:
                  description: 'AppUser info'
                  type: object
                  properties:
                    id:
                      type: string
                      minLength: 1
                  required:
                    - id
  /measurement:
    post:
      summary: Record Measurement. Allows for appUser specification of value type and asserts type-correctness on the server side.
      tags: []
      responses:
        '201':
          description: Created
          content:
            application/json:
                schema:
                  description: 'Creation message'
                  type: object
                  properties:
                    message:
                      type: string
                      minLength: 1
                  required:
                    - message
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                description: 'Error Cause'
                type: object
                properties:
                  message:
                    type: string
                    minLength: 1
                required:
                  - message
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                description: 'Error Cause'
                type: object
                properties:
                  message:
                    type: string
                    minLength: 1
                required:
                  - message
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                description: 'Error Cause'
                type: object
                properties:
                  message:
                    type: string
                    minLength: 1
                required:
                  - message
      operationId: post-measurement
      security:
        - import-key: []
      requestBody:
        content:
          application/json:
            schema:
              description: 'Measurement Request Contents'
              type: object
              properties:
                appUserID:
                  type: string
                  minLength: 1
                data:
                  type: object
                  required:
                    - date
                    - value
                    - source
                  properties:
                    date:
                      type: number
                    value:
                      type: number
                    source:
                      type: string
                    subtype: 
                      type: string
              required:
                - appUserID
                - data
components:
  schemas: {}
  securitySchemes:
    import-key:
      name: Authorization
      type: apiKey
      in: header
